### ISSUE TITLE
I cannot install vue-tools

### ISSUE THREAD

**Issue by kongmengfei** [vuejs/devtools#1539]
I am a newbee. i am trying to install Vue Devtools but Fail

Below is my cmd:

```
PS D:\sofdtware\github\vue-xuexi> npm install -g @vue/devtools
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
D:\sofdtware\nodejs\vue-devtools -> D:\sofdtware\nodejs\node_modules\@vue\devtools\bin.js

> core-js@3.16.1 postinstall D:\sofdtware\nodejs\node_modules\@vue\devtools\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://paypal.me/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.3.3 postinstall D:\sofdtware\nodejs\node_modules\@vue\devtools\node_modules\electron
> node install.js

(node:1216) UnhandledPromiseRejectionWarning: RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (D:\sofdtware\nvm\v14.17.5\node_modules\@vue\devtools\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (D:\sofdtware\nvm\v14.17.5\node_modules\@vue\devtools\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ @vue/devtools@5.3.4
added 189 packages from 140 contributors in 117.122s
PS D:\sofdtware\github\vue-xuexi> 

```
my nodejs version:  
`PS D:\sofdtware\github\vue-xuexi> node -v
v14.17.5`

Can you help me?

**Comment by konpeki622** [comment]
Maybe this solution is helpful to you.

https://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset

**Comment by Tanimodori** [comment]
This is caused by electron trying to download its binary. Setup a mirror may help:

```cmd
npm config set electron_mirror https://npmmirror.com/mirrors/electron/
```
