### ISSUE TITLE
Cannot build locally the extension

### ISSUE THREAD

**Issue by pascencio** [vuejs/devtools#1562]
### Version
5.3.4

### Browser and OS info
Chrome 87.0.4280.66 / Linux 5.12.19-1-MANJARO

### Steps to reproduce
npm install
npm run build

### What is expected?
Build extension successfully

### What is actually happening?
I'm getting the following error:

```shell
> vue-devtools@5.3.4 build /tmp/devtools-5.3.4
> cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--progress', '--hide-modules' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-devtools@5.3.4 build: `cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-devtools@5.3.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---
I tried install dependencies inside `package/shell-chrome` directory, but doesn't work because there is some local packages that I can install.

**Comment by konpeki622** [comment]
See #1143 .

> 这个问题是CMD无法识别webpack命令，需要下载webpack，全局安装的webpack没用，使用yarn add -D -W webpack-cli下载webpack,然后在npm run build，这个需要的时间可能比较长，有可能需要5分钟耐心等待

The problem is that CMD cannot recognize the `webpack` command and you need to install webpack. The global installation is unvalidable, instead you can use `yarn add -D -W webpack-cli` to install it and then run build. It may take a long time, please wait patiently.
