### ISSUE TITLE
"This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota" with Vue 3

### ISSUE THREAD

**Issue by JetForMe** [vuejs/devtools#1651]
### Version
6.0.0-beta.21

### Browser and OS info
Chrome 96.0.4664.110 (Official Build) (x86_64 translated), macOS 12.1

### Steps to reproduce
Use DevTools with Vue 3/Vite?

I'm developing a Vue 3/Vite-based app, and DevTools now spams the VSCode debug console with hundreds of this:

```
[69927:259:0101/193341.389529:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.390114:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.390174:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.390863:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.390928:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.390957:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.391031:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
```

### What is expected?
Not this

### What is actually happening?
What was described above.

---
For what it's worth, those hundreds of lines were preceded by this:

```
[69927:259:0101/193341.198885:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.199204:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.199249:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200481:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200537:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200667:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200698:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200725:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200753:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200866:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
[69927:259:0101/193341.200901:ERROR:CONSOLE(0)] "Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/devtools.js:2:836027", source: chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/devtools.html#/app/app/inspector/components (0)
```

**Comment by Akryum** [comment]
This is a chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1205278
