### ISSUE TITLE
store.subscribeAction is not a function

### ISSUE THREAD

**Issue by davestewart** [vuejs/devtools#1695]
### Version
6.0.3

### Browser and OS info
Chrome 98

### Steps to reproduce
Set a property `$store` on the Vue prototype:

```js
Vue.prototype.$store = {}
```

### What is expected?
I should be able to use a custom store without DevTools erroring 

### What is actually happening?

VueDevtools assumes this is a Vuex store (with `subscribeAction`) and this error appears when the page loads:

```
TypeError: store.subscribeAction is not a function
    at backend.js:4836:13
    at addPlugin (backend.js:2810:7)
    at async Object.<anonymous> (backend.js:2016:5)
```

---

I can add a no-op and it's fine, but I don't think devtools should be making assumptions about what `$store` may be in my app.

**Comment by davestewart** [comment]
I can submit a PR if easier, but likely one likely of code...
