### ISSUE TITLE
Vue Devtools randomly stops working

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/devtools#1697]
### Version
6.0.0
and
6.0.0 beta 21

I also tried out the legacy v5.3.4 which is where I first experienced this recently, very similar problem.

### Browser and OS info
Chrome Version 98.0.4758.80 (Official Build) (x86_64)
Mac Catalina 10.15.7 (19H1519)

### Steps to reproduce
1. Open Chrome DevTools
2. Open web page using Vue (in dev env)
3. Navigate around
4. Sometimes result is Vue Devtools panel is empty and requires reloading the Chrome Devtools window.
5. Another option is to reload the page
6. Result is Vue Devtools panel is empty and requires reloading the Chrome Devtools window.

In particular, if I'm in a Vue site, then log off the site (which reloads the page), every single time the Vue Devtools panel goes blank and requires reloading the Chrome Devtools window.

### What is expected?
It should not just stop working randomly. It should not go blank and require reloading the Chrome Devtools. 

### What is actually happening?
It stops working. The tab is there, but it just shows an empty panel with some kind of default image.

---
This has been happening to me all the time, regularly every few minutes or so. Some situations the page needs to reload, and that's when it happens more often than when just navigating around.

The Chrome store does not have Vue Devtools 6.0.4, it's still on v6.0.0. So until that is updated I cannot test the latest build. I have also tried changing my Devtools theme and uninstalled, reinstalled the extension as that helped some people in the other Issues. None of those suggestions worked.

Screenshot of the blank panel v6.0.0 and v6.0.0 beta 21
![image](https://user-images.githubusercontent.com/14927668/153275204-1eabc210-3408-4631-afb4-fc7d175dd502.png)

Screenshot of the panel v5.3.4
![image](https://user-images.githubusercontent.com/14927668/153279266-d40ce68e-9814-48ce-b5c1-4f021bfb938c.png)

**Comment by Akryum** [comment]
Did you try on Firefox to see if it is also affected?

**Comment by Akryum** [comment]
Could you please provide a runnable reproduction so I can run the devtools on it? Thanks

**Comment by webdevnerdstuff** [comment]
@Akryum I tested it on Firefox and have not been able to replicate the problem. It is using v6.0.4. So perhaps it's specific too Chrome, or somewhere between v6.0.0. and v6.0.4 fixed the issue?

I'm not sure what I can provide you for a runnable reproduction. I provide the steps I have taken, and I'm able to replicate it by just reloading the page at any time. I cannot provide you the code as this is my works site. 

I'm going to try loading v6.0.4 from the source code next to see if that changes anything. I assume to use this directories files? https://github.com/vuejs/devtools/tree/main/packages/shell-chrome

**Comment by Akryum** [comment]
Here is some documentation about how to build and test the repo: https://devtools.vuejs.org/guide/contributing.html

**Comment by webdevnerdstuff** [comment]
I'll set it up when I get some free time. Might not be until the weekend though.

**Comment by rudongsu** [comment]
I am experiencing the same issues with 6.0.0 beta 21 on Chrome. Navigating between my vue.js pages would randomly stop Devtools from working and it throws 'TypeError: sub is not a function' exception in the console.

**Comment by Akryum** [comment]
@rudongsu There is no `sub()` call in the devtools so it might come from your page (either in your code or in a library you are using). Still, without a runnable reproduction there is nothing I can do.

**Comment by rudongsu** [comment]
> @rudongsu maybe your issue is #1686

Yes! I realised that I was on the old version of Vuex. Just wondering when is the latest build (6.0.5) gonna be available in Chrome Web Store?

**Comment by jiaqidegege** [comment]
Same issue, when I reload page, the devtool get blank. Also, if I reload chrome devtool, it worked again.

**Comment by frankdai** [comment]
@Akryum 
I can reproduce sub is not a function issue. 
I am using 3.0.1 VueX, which has essentially this code:

`this._actionSubscribers.forEach(function (sub) { return sub(action, this$1.state); });`

While newest version of devtools will call subscribeAction with object instead:

```javascript
store.subscribeAction({
  before: (action, state) => {
    console.log(before action ${action.type})
  },
  after: (action, state) => {
    console.log(after action ${action.type})
  }
})
```
So this._actionSubscribers will contain object and thus throw this error.

**Comment by ankitsrivas14** [comment]
> @rudongsu There is no `sub()` call in the devtools so it might come from your page (either in your code or in a library you are using). Still, without a runnable reproduction there is nothing I can do.

This is from vuex.esm.js
<img width="1002" alt="Screenshot 2022-02-13 at 11 30 17 AM" src="https://user-images.githubusercontent.com/67647761/153740909-b03f2aba-342e-4c75-b518-cf3da2b0386a.png">

**Comment by webdevnerdstuff** [comment]
My version has updated to v6.0.8 and still has the problem. I'm going to work on the text repo next.

**Comment by webdevnerdstuff** [comment]
So today when I went to start things up, I was getting some new errors in the console. This was on first page load.

backend.js:702
```An error occurred in hook getInspectorState registered by plugin org.vuejs.vue2-internal
callHandlers @ backend.js:702
await in callHandlers (async)
callHook @ backend.js:195
await in callHook (async)
getInspectorState @ backend.js:409
sendInspectorState @ backend.js:2416
(anonymous) @ backend.js:2289
await in (anonymous) (async)
emit @ backend.js:9962
_emit @ backend.js:6595
(anonymous) @ backend.js:6521
(anonymous) @ backend.js:6521
listener @ backend.js:13516
postMessage (async)
n @ proxy.js:1
```

backend.js:703 
```Error: Missing module "root" for path "root".
    at backend.js:5260:13
    at Array.reduce (<anonymous>)
    at getStoreModule (backend.js:5256:16)
    at backend.js:4859:26
    at handler (backend.js:679:16)
    at DevtoolsHookable.callHandlers (backend.js:700:17)
    at async DevtoolsApi.callHook (backend.js:195:17)
    at async DevtoolsApi.getInspectorState (backend.js:409:21)
    at async sendInspectorState (backend.js:2416:44)
```
	
I then forked and cloned the repo, and followed the directions for "Development" from this page: https://devtools.vuejs.org/guide/contributing.html

I ran `yarn run build:watch` and `yarn run dev:vue3` in parallel and the same problem was happening at http://localhost:8090/
I also ran `yarn run dev:vue2` which also had the same problem at it's localhost page.

After that, something with `yarn run dev:vue3` was making my browser go nuts, and/or something else was going on with my computer so I restarted it. Came back, and now the two errors from above are not happening, but the initial problem where Vue Devtools stops working was still happening. So I then again ran `yarn run build:watch` and `yarn run dev:vue3` (as well as `yarn run dev:vue2`), and once again the problem persisted. Reload the page, Vue Devtools stops working and I get the empty screen with the single graphic that I posted previously.

Even though my extension from the Chrome store was at v6.0.8, I still proceeded to test out the "Testing as Chrome addon" step from the link you provided. I loaded the unpackaged extension, loaded up the vue site, and the problem is still happening when reloading the page.

So I then decided to look at the scripts the extension is running. I loaded up `devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@7f0488e8ba0d8e019187c6325a16c29d9b7f4989/&can_dock=true&panel=elements&dockSide=undocked (iframe)` and there was a persisten error as followed after opening my vue project.

```[shared data] Master init in progress...
shared-data.ts:105 [shared data] Master init complete
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/build/devtools.js:83473:28
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/build/devtools.js:83473:28
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/build/devtools.js:83473:28
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/build/devtools.js:83473:28
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.
```
	
Vue Devtools was working at this point. I reloaded the page to this
```Error handling response: TypeError: Cannot read properties of undefined (reading 'events')
    at chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/build/devtools.js:83473:28
chrome-extension://dehlobbiaibcfjcegbmdmppgklhnfdaa/devtools.html#/app/app-1/inspector/components:1 Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.
shared-data.ts:86 [shared data] Master init in progress...
shared-data.ts:105 [shared data] Master init complete
```

Vue Devtools was still working. I refreshed the page one more time and then this happened when Vue Devtools stopped working:

```Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
devtools.js:75 
devtools.js:75 
{isException: true, value: "TypeError: Cannot read properties of null (reading…')\n    at <anonymous>:5:32\n    at <anonymous>:7:7"}
isException: true
value: "TypeError: Cannot read properties of null (reading 'appendChild')\n    at <anonymous>:5:32\n    at <anonymous>:7:7"
[[Prototype]]: Object
shared-data.ts:86 [shared data] Master init in progress...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:122 [shared data] Master init retrying...
shared-data.ts:128 [shared data] Master init failed
(anonymous)	@	shared-data.ts:128
setInterval (async)		
(anonymous)	@	shared-data.ts:119
initSharedData	@	shared-data.ts:78
(anonymous)	@	app.ts:71
(anonymous)	@	WelcomeSlideshow.vue:20
__async	@	WelcomeSlideshow.vue:20
(anonymous)	@	app.ts:55
(anonymous)	@	devtools.js:41
(anonymous)	@	devtools.js:77
s	@	VM49:1
_onCallback	@	VM49:1
_onMessage	@	VM49:1
```

At this point, I'm not sure what else I can do to test this anymore. Vue Devtools is failing consistently and all of the time.

**Comment by webdevnerdstuff** [comment]
Then when I went to turn off the unpackaged extension I saw there was an extension error.

![extension-ss](https://user-images.githubusercontent.com/14927668/153776489-69d7f47a-3ab8-4b89-b4f1-bbf0ec547668.png)

**Comment by webdevnerdstuff** [comment]
Yet the Firefox v6.0.4 extension still works perfectly and as intended. Same vue projects tested with no problems. It only seems to be happening for me on Chrome.

**Comment by Akryum** [comment]
@webdevnerdstuff 

![image](https://user-images.githubusercontent.com/2798204/153843856-ab0803a9-38c0-48b6-9751-5b5924df1206.png)

You forgot to put the actual error messages here, I only see stack traces.

> I ran yarn run build:watch and yarn run dev:vue3 in parallel and the same problem was happening at http://localhost:8090/
I also ran yarn run dev:vue2 which also had the same problem at it's localhost page.

Were you inspecting the devtools development shell with the "real" devtools? What was the error?

**Comment by webdevnerdstuff** [comment]
@Akryum That is the least important part of that post. I wouldn't focus on that part. I didn't forget to give more details about it, as after I restarted my computer that error went away so I could not look into it further.

**Comment by webdevnerdstuff** [comment]
So now I just updated Chrome to Version 98.0.4758.102 (Official Build) (x86_64). Still have the problem, but now the error that I said went away after I rebooted my computer... is now back. This time I didn't accidentally miss copying the error it's giving me. How and if this relates to the other information I gave you, I would not know.

backend.js:702 
```An error occurred in hook getInspectorState registered by plugin org.vuejs.vue2-internal
callHandlers @ backend.js:702
await in callHandlers (async)
callHook @ backend.js:195
await in callHook (async)
getInspectorState @ backend.js:409
sendInspectorState @ backend.js:2416
(anonymous) @ backend.js:2289
await in (anonymous) (async)
emit @ backend.js:9962
_emit @ backend.js:6595
(anonymous) @ backend.js:6521
(anonymous) @ backend.js:6521
listener @ backend.js:13516
postMessage (async)
n @ proxy.js:1
```

backend.js:703
```Error: Missing module "root" for path "root".
    at backend.js:5260:13
    at Array.reduce (<anonymous>)
    at getStoreModule (backend.js:5256:16)
    at backend.js:4859:26
    at handler (backend.js:679:16)
    at DevtoolsHookable.callHandlers (backend.js:700:17)
    at async DevtoolsApi.callHook (backend.js:195:17)
    at async DevtoolsApi.getInspectorState (backend.js:409:21)
    at async sendInspectorState (backend.js:2416:44)
```

**Comment by Akryum** [comment]
So the error you have is actually #1669? (If it is, please try posting a reproduction, I don't reproduce it on the repo dev shell, maybe another reproduction could help me.) This shouldn't stop the devtools from working apart from the Vuex inspector, but your initial post suggested that the devtools stopped working altogether?

**Comment by webdevnerdstuff** [comment]
I think the latest version (v6.0.12) or another version in between may have resolved the issue. It hasn't been going blank for me anymore I think.  So this Issue might be resolved now.

**Comment by webdevnerdstuff** [comment]
Guess I spoke too soon. Was doing pretty good until today, where it's been having the issue again. Ugh.

**Comment by journeywithIT** [comment]
google

**Comment by NathanWailes** [comment]
I was just having this issue, it looks like it was because I was still using the Vue Devtools Beta (6.0.0.21).  When I uninstalled that and installed the latest version of Vue Devtools (the non-beta version), the problem went away.

**Comment by mdr1384** [comment]
Not sure if this is new/useful, but I have lately been seeing random "staleness" in the Vue dev tool (2.6.14) data values after using it for a couple hours including many page refreshes. The DOM view seems fine, just the data view gets "stale". Clicking "Force refresh" does not fix it, but closing the dev tool and reopening it seems to. This is in the Chrome browser 108.0.5359.73.

**Comment by Thinkro** [comment]
@mdr1384 same issue here

**Comment by joallard** [comment]
Running v6.4.5 on Firefox 108.0b9 (macOS 13) and I can confirm this has been happening to me for a while, getting the "disconnection" icon often. Switching tabs and letting it sit for a while, then coming back to it will often trigger the bug.

**Comment by bdanielbell** [comment]
I too am experiencing the same thing on Firefox latest, also the Vue tools keeps randomly doing a full refresh, and when it does, I lose my place and have to navigate back into whatever component or what not.  It is extremely annoying.  This never happened in earlier versions.

**Comment by djpowers** [comment]
@bdanielbell I was also experiencing the full refresh problem and came across this issue, but noticed it was reported separately in #1974. The fix for that has been merged and a new release was tagged in v6.5.0, but it doesn't seem to have made its way to AMO yet.

**Comment by striderwhitepderas** [comment]
I get the same issue, every 30 seconds it just reloads itself - SUPER annoying!

**Comment by bdanielbell** [comment]
Tried to build 6.5.0 extension for firefox, but it failed with all kinds of errors.  Not even going to bother trying to figure it out, I have too much work to do.  Going to remove 6.4.5 and fallback to the legacy version.  I can't deal with the constant crashing and refreshing anymore.

**Comment by bitfactory-oussama-fadlaoui** [comment]
Will this ever be picked up?

**Comment by philharmonie** [comment]
The issue is still persistent on latest Chrome version (118.0.5993.117 arm64), macOS Sonoma 14.0 (MacBook Pro 14" 2023 M2 Pro), Vue.js devtools Version 6.5.1, Vue 3.3.4.
I got all unexpected issues, that have been described here:
- Vue tab not appearing at all randomly
- Loading Spinner in Vue Tab forever randomly
- Component not loading randomly. When I click it, it says "Select a Component"

**Comment by xxholly32** [comment]
> The issue is still persistent on latest Chrome version (118.0.5993.117 arm64), macOS Sonoma 14.0 (MacBook Pro 14" 2023 M2 Pro), Vue.js devtools Version 6.5.1, Vue 3.3.4. I got all unexpected issues, that have been described here:
> 
> * Vue tab not appearing at all randomly
> * Loading Spinner in Vue Tab forever randomly
> * Component not loading randomly. When I click it, it says "Select a Component"

Vue.js devtools Version 6.6.1, Vue 3.4.5 , same problem

![录制_2024_02_20_09_31_08_691](https://github.com/vuejs/devtools/assets/6063358/bc800c05-151e-4575-87bb-1d31b7f5b2a2)

**Comment by n4ks** [comment]
After upgrading to Vue 3, the plugin constantly stop working, won't allow me to select an element, won't update the state. I literally have to close my browser after 1-2 minutes of working with the component or after refreshing the page. I've been using this plugin for over two years with Vue 2, but it's becoming impossible to use it with Vue 3.

**Comment by bitfactory-oussama-fadlaoui** [comment]
How is this issue, as important as it is, being ignored by the development team...
