### ISSUE TITLE
Cannot read properties of null (reading 'instanceMap')

### ISSUE THREAD

**Issue by ssgnoe** [vuejs/devtools#1711]
### Version
6.0.6

### Browser and OS info
Chrome  98.0.4758.80 (Offizieller Build) (x86_64) on Mac OS 12.2

### Steps to reproduce
On every Nuxt.js (2.15.7) Application I have , the Devtools crashes after some changes in Code after Livereloads and click on a component which I changed recently.

Error:
VM37312 backend.js:2198 Uncaught TypeError: Cannot read properties of null (reading 'instanceMap')
    at Bridge.<anonymous> (VM37312 backend.js:2198:55)
    at Bridge.emit (VM37312 backend.js:9851:5)
    at Bridge._emit (VM37312 backend.js:6486:12)
    at VM37312 backend.js:6412:42
    at Array.forEach (<anonymous>)
    at VM37312 backend.js:6412:18
    at listener (VM37312 backend.js:13405:13)

After this crash I'm not able to get it working back again. After Reload it can not detect Vue.js on page. Restart Browser or Reinstall Extension works for about 30 Minutes, than it crashes again.

### What is expected?
No crash, previous version worked fine

### What is actually happening?
Crashes

**Comment by ssgnoe** [comment]
Maybe the problem just comes up, when Nuxt.js has an Error. Than pagereload is not enough to reload Devtools Component Structure. Clicking on the NuxtError Component displays a loader and logs the Error on top.

**Comment by Akryum** [comment]
Please provide a runnable reproduction. Thanks

**Comment by fango256** [comment]
Just to say, we are not using nuxt and see this error consistently - every click on a component in the dev tools throws this 7+ times for us. Makes the tools unusable at the moment (perpetual loading bar).

Cannot easily create repro as it's a large enterprise app.

**Comment by Akryum** [comment]
You can always create a reproduction and by doing so finding the combination of libraries you use and setup code that makes this issue happen.

**Comment by wrench1815** [comment]
Yes i see this error ocassionally. Let's say you update a component in your project like added a new prop in it. And then your try to manipulate the options of the component in devtools it will throw the error. Why? 'cuz for some reasons it is not able to track the changes that happened in the Component.

As for creating a reproduction, well from above you can see it is not possible to create one. It just happens like at runtime? This has nothing to do with any library.

**Comment by Evertvdw** [comment]
I am also having this issue consistently, also a large enterprise app. If I have some time left I will try to create a reproduction project, but that will probably take some time.

**Comment by Evertvdw** [comment]
@Akryum I have not yet created a reproduction but I can see in the code where it goes wrong. In my application the `COMPONENT_ADDED` [hook ](https://github.com/vuejs/devtools/blob/main/packages/app-backend-core/src/index.ts#L168) is called before this line [here ](https://github.com/vuejs/devtools/blob/main/packages/app-backend-core/src/app.ts#L107) where the `selectApp` function is called.

This means that the `currentAppRecord` is null when the `walkComponentParents` function is called inside the `mark` function [here](https://github.com/vuejs/devtools/blob/main/packages/app-backend-vue3/src/components/tree.ts#L226).

Normally the `selectApp` is called before and this problem does not occur. I cannot recreate a reproduction yet. I have currently stripped down my application to a bare minimum, just showing a blank page (using Quasar), so there is something in my setup that is causing this, I will try to dig a little deeper.

But maybe this is enough for you already to create a fix.

**Comment by BenceSzalai** [comment]
@Evertvdw : I am having the same issue also using Quasar for the very same reason as you have described.

But my error stack trace does not look like the one in the original issue, but more like #1892.

Not sure if these two are related or not...?

@Evertvdw: can you check if your stack trace is like https://github.com/vuejs/devtools/issues/1711#issue-1132108341 or like https://github.com/vuejs/devtools/issues/1892#issue-1276477020 ?

**Comment by Evertvdw** [comment]
@BenceSzalai  Here is my error stack:
![image](https://user-images.githubusercontent.com/5757159/223093695-1979affd-da3c-4028-acb2-60d755cadd15.png)

I am just using the router-view normally, no `keep-alive` used anywhere.

**Comment by BenceSzalai** [comment]
@Evertvdw Based on the stack trace your issue is #1892 as well, instead of this one.

**Comment by ishaiavrahami** [comment]
same here
