### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by throrin19** [vuejs/devtools#1712]
### Version
6.0.6

### Browser and OS info
Chrome 98 / MacOs 11.6

### Steps to reproduce
- Launch an Vue 2 app
- Move to another route

### What is expected?
No error

### What is actually happening?
VueDevTools error :  

```
An error occurred in hook getInspectorTree registered by plugin org.vuejs.vue2-internal
```

```
backend.js:702 TypeError: Cannot read properties of undefined (reading 'map')
    at backend.js:4742:53
    at handler (backend.js:678:16)
    at DevtoolsHookable.callHandlers (backend.js:699:17)
    at DevtoolsApi.callHook (backend.js:194:26)
    at async DevtoolsApi.getInspectorTree (backend.js:396:21)
    at async sendInspectorTree (backend.js:2380:21)
```

**Comment by Akryum** [comment]
Please provide a runnable reproduction. Thank

**Comment by Akryum** [comment]
Create a repo or a zip with the same libraries you are using that shows the issue you have. I have to be able to run it to investigate the issue.
