### ISSUE TITLE
Console Errors in Vivaldi (chromium)

### ISSUE THREAD

**Issue by impaect** [vuejs/devtools#1786]
### Version
6.0.13

### Browser and OS info
Vivaldi	5.1.2567.49 Debian GNU/Linux 11 KDE Plasma Version: 5.20.5 KDE Frameworks Version: 5.78.0 Qt Version: 5.15.2 Kernel Version: 5.10.0-1025-oem OS Type: 64-bit

### Steps to reproduce
On Random occasions in developement i get multiple 

> Cannot destructure property 'groupId' of 'appRecord.perfGroupIds.get(...)' as it is undefined.

 errors in the Console. This started happening today. Updating to a newer vivaldi didnt resolve the issue.

These Errors are happening en masse and clutter the Console when navigating in my app. I dont get these in Google Chrome tho.

This is the Stack trace of the first couple Frames. It originated from Vue router further down

```
backend.js:2847 TypeError: Cannot destructure property 'groupId' of 'appRecord.perfGroupIds.get(...)' as it is undefined.
    at performanceMarkEnd (backend.js:2784:7)
    at async Object.<anonymous> (backend.js:2038:5)
performanceMarkEnd	@	backend.js:2847
await in performanceMarkEnd (async)		
(anonymous)	@	backend.js:2038
emit	@	VM23751:1
handler	@	backend.js:4326
invokeWithErrorHandling	@	vue.runtime.esm.js?2b0e:1863
callHook	@	vue.runtime.esm.js?2b0e:4235
Vue.$destroy	@	vue.runtime.esm.js?2b0e:4018
destroy	@	vue.runtime.esm.js?2b0e:3178
invokeDestroyHook	@	vue.runtime.esm.js?2b0e:6158
removeVnodes	@	vue.runtime.esm.js?2b0e:6174
...
```

### What is expected?
These errors should not occur

### What is actually happening?
Everything seems to work fine

**Comment by gitdust** [comment]
have the same problem today

**Comment by artfromlife** [comment]
have the same problem today

**Comment by elzodxon** [comment]
Have the same issue.

**Comment by peterramsis** [comment]
Have the same issue.
