### ISSUE TITLE
maxcallstacksize

### ISSUE THREAD

**Issue by sarkiroka** [vuejs/devtools#1810]
### Version
6.1.3

### Browser and OS info
chrome 99 / ubuntu 20.04

### Steps to reproduce
page load, or any click

### What is expected?
no error

### What is actually happening?
VM11550:1 RangeError: Maximum call stack size exceeded
    at cloneObjectDeep (backend.js:8902:25)
    at cloneDeep (backend.js:8893:14)
    at cloneObjectDeep (backend.js:8909:18)
    at cloneDeep (backend.js:8893:14)
    at cloneArrayDeep (backend.js:8919:14)
    at cloneDeep (backend.js:8895:14)
    at cloneObjectDeep (backend.js:8909:18)
    at cloneDeep (backend.js:8893:14)
    at cloneObjectDeep (backend.js:8909:18)
    at cloneDeep (backend.js:8893:14)

**Comment by sarkiroka** [comment]
Please release an update from the previous version where there is an option to disable automatic updates. It drives me crazy that I put the previous version up but it automatically updates. The new one is not completely unusable, and it's very nice and everything, but it has a lot of bugs. Disturbingly so. I'd like to use the older, more stable version. What can I do to do this?

**Comment by Akryum** [comment]
Read the docs?

**Comment by feijuncheng** [comment]
I had the same problem, when copying a doubly linked list

**Comment by okj579** [comment]
This is occurring because 'clone-deep' can't handle circular references. Is there a reason why the lodash cloneDeep wouldn't work here?

[packages/app-backend-vue2/src/plugin.ts#L167](https://github.com/vuejs/devtools/blob/ba54bb770a829429226a630dd5dbedcf596f27ef/packages/app-backend-vue2/src/plugin.ts#L167)
