### ISSUE TITLE
Dev tools fails to inspect component containing objects with "_isVue", throws errors

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/devtools#1822]
### Version
6.1.4

### Browser and OS info
Chrome 99.0.4844.74

### Steps to reproduce
1. Create a Vue 2 component
2. Create a class that includes a `public _isVue = true;`
3. Instantiate this class in your component
4. Go to the inspector, and click on your component in the component tress
5. Observe infinite loading
6. Observe console errors

### What is expected?
That the component is inspected.

### What is actually happening?
The inspector will infinitely load for that component, and the following errors show up in the console:

> backend.js:7028 [Bridge] Error in listener for event b:component:selected-data with args: ['app-1:308']
wrappedListener @ backend.js:7028
await in wrappedListener (async)
emit @ backend.js:10542
_emit @ backend.js:7098
(anonymous) @ backend.js:7011
(anonymous) @ backend.js:7011
listener @ backend.js:14172
postMessage (async)
n @ proxy.js:1

> backend.js:7029 TypeError: Cannot read properties of undefined (reading 'props')
    at processProps (backend.js:3982:35)
    at getInstanceState (backend.js:3925:10)
    at Object.getCustomInstanceDetails (backend.js:3933:17)
    at getCustomInstanceDetails (backend.js:6908:36)
    at backend.js:8356:82
    at EncodeCache.cache (backend.js:8252:22)
    at Object.replacer (backend.js:8356:26)
    at encode (backend.js:8006:38)
    at encode (backend.js:8017:19)
    at encode (backend.js:8007:21)

![image](https://user-images.githubusercontent.com/1400380/161441677-33c98995-00c9-4af9-905d-02abdd96e939.png)

---
This is a workaround prevent Vue making an object contained in a component reactive when it doesn't need to be, or when such reactivity causes crippling performance concerns, such as with Babylon.js. It works as expected.

This was not a problem before the dev tools update.

**Comment by tehnorm** [comment]
I'm seeing the same thing. Was there ever a workaround or solution for this issue?

**Comment by Lyon1011** [comment]
我在运行一个使用了vue的简单的html文件时尝试使用了devtool并产生了同样的问题，而并非是包含了_isVue的组件，所以是完全没有解决方法是吗

**Comment by douglasg14b** [comment]
Yeah, still an issue, when components like this are encountered the dev tools just break & lock up now. Great stuff.

**Comment by Zorii4** [comment]
The same happenes with dynamic <components> in Nuxt.js. 
Is there any solution?
