### ISSUE TITLE
Vue Devtools not able to load Pinia

### ISSUE THREAD

**Issue by leslie-begaone** [vuejs/devtools#1964]
### Version
6.4.3

### Browser and OS info
Chrome Version 106.0.5249.91 / Windows 10

### Steps to reproduce
1. Open a Vue app / page.
2. Open Chrome inspector Vue Devtools 6.4.3
3. Vue Devtools will try to load but throws an error when running connectBridge

### What is expected?
Vue JS Dev tools to load normally and show all 3 - Components, Pinia and Timeline.

### What is actually happening?
Upon opening Vue Devtools Page in Chrome inspector after the page is loaded without any errors, the browser throws the following error: 

backend.js:2587 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at connectBridge (backend.js:2587:23)
    at connect (backend.js:1993:3)

As a result Vue Devtools have loaded Components and Timeline, but Pinia isn't loaded.

################################

backend.js:2587:23 

pageTitleObserver.observe(document.querySelector('title'), {
      subtree: true,
      characterData: true,
      childList: true
    });

#################################

**Comment by leslie-begaone** [comment]
Tried installing Vue Devtools beta via the Chrome Extension store and error doesn't come up on opening Devtools and indeed Pinia gets loaded correctly. However, the beta Devtools breaks Vue Router with any route changes - api.now is not a function error  is thrown and the app doesn't work.

**Comment by leslie-begaone** [comment]
Found a temporary workaround by reinstalling Vue Router via npm i vue-router@4 and using the Vue Devtools Beta Version

**Comment by cavatron** [comment]
if you're like me and ended reading this issue after pinia wouldnt load in devtools, make sure your `index.html` file has a `<title>` tag. 

It seems this was fixed by [this commit](https://github.com/vuejs/devtools/commit/44620cc7aecd0ed083431dd9de05f075950afd82)

**Comment by Pijuli** [comment]
I'm in the same situation.

Pinia is not showing in vue devtools stable
If I install the beta version I get the api.now is not a function. So it breaks even more.
I had, already, a <title> tag in index.html . So not a fix for me

Chrome 107.0.5304.68 / Ubuntu 20.04
Pinia 2.0.23
Vue 3.2.45
Ionic/vue 6.3.6

@leslie-begaone could you please consider reopening the issue?
