### ISSUE TITLE
Pinia doesn't show up devtools in Nuxt 3/Vue 3 app

### ISSUE THREAD

**Issue by wandolch** [vuejs/devtools#2132]
### Vue devtools version

6.5.1

### Link to minimal reproduction

https://github.com/wandolch/nuxt3-playground

### Steps to reproduce & screenshots

Nuxt 3 application that uses pinia 2.1.7 and @pinia/nuxt 0.5.1

<img width="293" alt="Screenshot 2024-01-23 at 11 00 28" src="https://github.com/vuejs/devtools/assets/16466102/366f0e85-cc40-4992-beed-1da3f09d3e43">

Create any Pinia store and use it in a component, hydration enabled. 

Vue devtools won't recognise that Pinia exists on client side:

<img width="601" alt="Screenshot 2024-01-23 at 11 02 18" src="https://github.com/vuejs/devtools/assets/16466102/ae0e402c-50ae-4ef9-b4c5-c2965493391b">

There was a similar [ticket](https://github.com/vuejs/devtools/issues/1839) in a SPA vue, the reason was that people should define Pinia after mounting the app. In Nuxt it's not the case because Pinia is degined inside @pinia/nuxt and I don't have control over it.

### What is expected?

Pinia should appear in vue devtools.

### What is actually happening?

Pinia doesn't appear in vue devtools, it's impossible to debug it.

### System Info

```shell
System:
    OS: macOS 13.6.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.81 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.0 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.6
  npmPackages:
    vue: ^3.4.10 => 3.4.14
```

**Comment by azmatzuberi** [comment]
I was having a similar issue and I just put the module at the very top and it worked. Although, I see you only have one module.

**Comment by jdbdnz** [comment]
Samesies

**Comment by rileyphoenixbytes** [comment]
Having the same problem, a solution would be very much appreciated.

**Comment by codeplayer71** [comment]
I have the same problem, has anything been done here yet?

**Comment by outlabsio** [comment]
Same issue here. The other dev on my team with the same environment can see it but I cant. I have another project that works fine.

**Comment by outlabsio** [comment]
Also, If im working on a project where the Pinia dev tools does appear and then swap over to a project where the pinia dev tools are not showing, the following error appears when opening up the nuxt devtools. Not sure if this is helpful 


entry.Li7bMdxw.js:17 [nuxt] error caught during app initialization Error: Page not found: /modules/pinia
    at oc (entry.Li7bMdxw.js:17:48540)
    at entry.Li7bMdxw.js:34:19262
    at r (entry.Li7bMdxw.js:17:30252)
    at Object.runWithContext (entry.Li7bMdxw.js:13:26767)
    at Rw (entry.Li7bMdxw.js:17:30282)
    at entry.Li7bMdxw.js:17:28578
    at Sp.run (entry.Li7bMdxw.js:9:267)
    at Object.runWithContext (entry.Li7bMdxw.js:17:28570)
    at entry.Li7bMdxw.js:34:19240
    at entry.Li7bMdxw.js:21:20524

**Comment by devmadhavv** [comment]
You can find pinia in Nuxt devtools
