### ISSUE TITLE
Standalone version of devtools not launching on bun

### ISSUE THREAD

**Issue by rp1231** [vuejs/devtools#491]
I get this error:
```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\lenovo\.bun\install\global\node_modules\electron\index.js:17:11)
    at Object.<anonymous> (C:\Users\lenovo\.bun\install\global\node_modules\electron\index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at cjsLoader (node:internal/modules/esm/translators:318:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

```
I tried deleting hte entire node_modules directory and reinstalling, but it's not working.

**Comment by Lootjs** [comment]
Have you tried `npm -g remove electron` ?

**Comment by Lootjs** [comment]
Great! Maybe you could make a PR and mention the solution in https://github.com/vuejs/devtools-next/blob/main/docs/help/troubleshooting.md. What do you think?

**Comment by alexzhang1030** [comment]
Let's track if someone else reports this issue.

**Comment by alexzhang1030** [comment]
https://github.com/oven-sh/bun/issues/1588, looks like an upstream issue
