### ISSUE TITLE
 reactivity.esm-bundler.js:1024 Uncaught (in promise) RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zh-or** [vuejs/devtools#689]
vue version:3.5.12
pinia version:2.1.7
devtools version: 7.6.3
chrome version:130.0.6723.92 (not matter much)
error log:
```
reactivity.esm-bundler.js:1024 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at MutableReactiveHandler.ownKeys (reactivity.esm-bundler.js:1024:1)
    at Function.getOwnPropertySymbols (<anonymous>)
    at traverse (reactivity.esm-bundler.js:1883:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
    at traverse (reactivity.esm-bundler.js:1881:1)
```

![image](https://github.com/user-attachments/assets/8db3578d-ea2e-4280-b7b1-383a35b2c098)

触发堆栈溢出的代码, 关闭devtools后则不会报错!
```
import {h, render} from 'vue';
import com from 'xxx';


function mount() {
    render(h(com, {}), document.createElement('div'));
}

mount();

```
但是这段代码单独拿出来使用又没有问题!

**Comment by webfansplz** [comment]
方便提供一个最小可复现 Demo 吗？🙏
