### ISSUE TITLE
7.6.6: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by simon-kolkmann** [vuejs/devtools#716]
`vite-plugin-vue-devtools@7.6.6` breaks vite (`5.4.10`):

```
> vite

error when starting dev server:
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at configureServer (file:///app/client/node_modules/vite-plugin-vue-devtools/node_modules/vite-plugin-inspect/dist/index.mjs:1403:12)
    at configureServer (file:///app/client/node_modules/vite-plugin-vue-devtools/node_modules/vite-plugin-inspect/dist/index.mjs:1489:19)
    at _createServer (file:///app/client/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:63080:26)
    at async CAC.<anonymous> (file:///app/client/node_modules/vite/dist/node/cli.js:735:20)
```

Minimal `vite.config.js`:

```js
import { defineConfig } from 'vite'
import vueDevTools from 'vite-plugin-vue-devtools'

export default defineConfig(() => {
	return {
		plugins: [vueDevTools()]
	}
})
```

A downgrade to `7.6.5` fixes the issue.

**Comment by webfansplz** [comment]
Thanks for the feedback. Fixed in v7.6.7
